name: 🚀 Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Esto ejecutará 'tsc -b' y luego 'vite build'

      - name: Check build output
        run: |
          echo "📂 Archivos en dist/:"
          ls -la dist/  # Asegúrate de que los archivos estén en 'dist/'

      - name: Deploy build folder to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/" # Cambia a 'dist/' si esa es la carpeta generada
          target: "/var/www/"

      - name: Final log
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "🚀 Despliegue completado."
            cd /var/www/colegiocumbre && ls -la
